  apilambdasavedynamodb:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:375983427419:applications/api-lambda-save-dynamodb
        SemanticVersion: 2.1.0
      Parameters: 
        # (Optional) Cross-origin resource sharing (CORS) Origin. You can specify a single origin, all "*" or leave empty and no CORS will be applied.
        # CorsOrigin: '\'*'' # Uncomment to override default value
        # (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
        TableName: email_signup  
      