AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  PJhandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PJhandler
      Handler: PJ/handler.handler
      Timeout: 60
      Policies:
      - Statement:
        - Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          Resource:
            Fn::Sub:
            - arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
            - tableName: contact_us
          Effect: Allow
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Resource:
            Fn::Sub:
            - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
            - functionName: PJhandler
          Effect: Allow
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 8ce5d17c-b64d-4f49-9705-79e432bb63a4
      Runtime: nodejs14.10
      Events:
        contactUsEvent:
          Type: Api
          Properties:
            Path: /contact
            Method: post
      Description: Invokes functions defined in PJ/handler.js in project PJ-1-0-0. Generated by Sigma.
  PJviewer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PJviewer
      Handler: PJ/viewer.handler
      Timeout: 60
      Policies:
      - Statement:
        - Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          Resource:
            Fn::Sub:
            - arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
            - tableName: contact_us
          Effect: Allow
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Resource:
            Fn::Sub:
            - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
            - functionName: PJviewer
          Effect: Allow
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 8ce5d17c-b64d-4f49-9705-79e432bb63a4
      Runtime: nodejs6.10
      Events:
        contactUsEvent:
          Type: Api
          Properties:
            Path: /view
            Method: get
      Description: Invokes functions defined in PJ/viewer.js in project PJ-1-0-0. Generated by Sigma.
  ddbcontactus:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - KeyType: HASH
        AttributeName: email
      TableName: contact_us
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      ProvisionedThroughput:
        WriteCapacityUnits: 1
        ReadCapacityUnits: 1
Description: This template creates the stack for project PJ-1-0-0. Generated by Sigma